### ISSUE TITLE
无法正常显示

### ISSUE THREAD

**Issue by JoeScandium** [magicdawn/bilibili-app-recommend#10]
如图，刷新和删除缓存还有重新安装脚本均没用
![屏幕截图_20221118_183148](https://user-images.githubusercontent.com/40695113/202684020-0704b42d-a575-46eb-99ce-f475b76578d0.png)

**Comment by magicdawn** [comment]
环境: 系统 / 浏览器 / monkey插件(TamperMonkey 还是啥) ?

**Comment by JoeScandium** [comment]
Windows 11 专业版 22H2 22621.819
Chrome 107.0.5304.107 （64 位）
TamperMonkey v4.18.0

**Comment by JoeScandium** [comment]
刷新的一瞬间是可以看到有封面显示的，不过一会就变成上述图片的样子，点击也是没有反应

**Comment by magicdawn** [comment]
我复现了, 接口报错. 我加了下重试, 稍候发布.

**Comment by magicdawn** [comment]
try v0.5.2 https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend
