### ISSUE TITLE
[Feature Request]: 根据up粉丝数量推荐

### ISSUE THREAD

**Issue by kevinhwang91** [magicdawn/bilibili-app-recommend#100]
### 环境

浏览器: Chrome
浏览器版本: 125.0.6422.112 (Official Build) (64-bit)
脚本管理器: TamperMonkey
脚本版本:  0.22.3

### 问题详细描述

场景：
个人认为up粉丝在1万-10万的视频更为有价值，且质量能保证。也更容易发现有趣的up。默认的推荐很多都是大up老朋友了

**Comment by magicdawn** [comment]
推荐后端的能力, 小小脚本办不到啊~

**Comment by magicdawn** [comment]
有需求反馈给b站客服吧...

**Comment by aiden-leong** [comment]
> 推荐后端的能力, 小小脚本办不到啊~

虽然这个issue已经被close掉了，但我在过滤器方面有类似的想法：

- [ ] 允许设置一个视频作者粉丝数范围，不在范围内的不予显示。

这样可以过滤掉一些营销号，以及一些博眼球的黑灰产垃圾号。
