### ISSUE TITLE
[BUG]: 预览手机端推送视频时，若有番剧推荐则会无法预览并反复提示“啥都木有”错误，建议对番剧推荐关闭预览功能

### ISSUE THREAD

**Issue by lemon-sundae** [magicdawn/bilibili-app-recommend#101]
### 环境

浏览器: Arc (Chromium)
浏览器版本: Version 1.44.3 (50502) (Chromium Engine Version 125.0.6422.113)
脚本管理器: TamperMonkey
脚本版本: v0.22.5

### 问题详细描述

鼠标悬停（或其他方式）于番剧推荐卡片上进行预览

**Comment by magicdawn** [comment]
GreasyFork已有反馈, 开发版已解决.

https://github.com/magicdawn/bilibili-app-recommend/raw/release-nightly/bilibili-app-recommend.mini.user.js

**Comment by magicdawn** [comment]
patch released.
