### ISSUE TITLE
[BUG]: 打开视频加载时有bug

### ISSUE THREAD

**Issue by TellMeaJoke** [magicdawn/bilibili-app-recommend#102]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)
edge 123.0.2420.81 (正式版本) (64 位)
TamperMonkey 5.2.0

### 问题详细描述

打开视频加载一两秒后,视频会黑掉重新加载页面,过程需要近10秒左右.

### 预期结果

关闭插件没有这个问题,希望在加载页面元素的时候,视频不需要黑屏重新加载.

**Comment by magicdawn** [comment]
是最新版么

> 脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/da7ff795-e8cb-41e6-bffa-8b1e1b9d3b4c)

----

还有此处设置选的是什么

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/5a58ddbf-4de9-4ce2-a396-fac28741ab0c)
