### ISSUE TITLE
[BUG]:“我不想看”功能无法正常工作

### ISSUE THREAD

**Issue by zjxian** [magicdawn/bilibili-app-recommend#103]
### 环境

浏览器: Chrome
浏览器版本: 版本 125.0.6422.142（正式版本） （64 位）
脚本管理器: TamperMonkey 5.1.1
脚本版本: 0.22.6

### 问题详细描述

点击任意视频，选择我不想看（向下的大拇指），出现的界面里，无论选择哪个理由，点击后/回车键提交后，始终提示“操作失败, 请重试 !!!”

### 预期结果

能够正常的标记视频为不想看的。

**Comment by magicdawn** [comment]
重新 access_key ....

**Comment by magicdawn** [comment]
亲测正常运行, closing this.
