### ISSUE TITLE
[BUG]:Windows11, chrome firefox Arc功能直接失效，UI变回b站默认主页了

### ISSUE THREAD

**Issue by ItoshikiGen** [magicdawn/bilibili-app-recommend#105]
### 环境

浏览器: Chrome Firefox Arc均最新版
脚本管理器: TamperMonkey
脚本版本: 最新版

### 问题详细描述

脚本直接失效了，像未安装一样。一开始怀疑和bilibili envolved冲突了但删了envolve之后依旧没法使用。
刚打开chrome试验了一下一开始用的脚本是三月份的版本就没问题，更新到今天的最新版之后也出问题了。
![图片](https://github.com/magicdawn/bilibili-app-recommend/assets/114046162/2d8e60a8-6910-4418-ab4a-c3e01bf8d5e1)
![图片](https://github.com/magicdawn/bilibili-app-recommend/assets/114046162/c11c9dfd-bd1e-4418-b54c-9fd7791e1e30)

**Comment by magicdawn** [comment]
无法重现...

能提供报错信息么, 空白处右键 - 检查 - 切换到 console tab, 应该有报错

**Comment by ItoshikiGen** [comment]
睡了一晚莫名其妙好了。。。抱歉麻烦了，没问题了。
