### ISSUE TITLE
[BUG]:视频推荐卡片在Firefox上出现样式错误

### ISSUE THREAD

**Issue by zxdrft6** [magicdawn/bilibili-app-recommend#109]
### 环境

浏览器: Firefox
浏览器版本: 127.0.1 (64 位)
脚本管理器: TamperMonkey 5.1.1
脚本版本: 0.24.0

### 问题详细描述

问题如同标题，发现在Firefox浏览器里出现了问题，按键错位，预览也似乎无法运作，如下图
![firfox](https://github.com/magicdawn/bilibili-app-recommend/assets/154341760/3c4d93f3-c69b-487c-a770-79e4b091866b)
同时启用的脚本只有Bilibili Evolved，但应该与此无关，我已经尝试禁用其他脚本，只启用bilibili-app-recommend，依然存在问题
另外在New Edge上的表现是正常的，如下图，两边的脚本管理器、脚本版本和启用的脚本及设置等基本是一致的
![edge](https://github.com/magicdawn/bilibili-app-recommend/assets/154341760/e99004df-e044-4569-8fb3-c86c393affbf)

希望大佬能够看一看是否存在这个问题

**Comment by magicdawn** [comment]
确实有这个问题, 我修一下, 感谢报告此问题.
