### ISSUE TITLE
能否调整一下内测版本首页下卡片的尺寸

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#11]
现在跟内测首页的卡片的尺寸不统一，希望可以调整一下
![image](https://user-images.githubusercontent.com/79258245/202694546-5b083dad-e17f-4f9f-bb0f-4d6d9160bdce.png)

**Comment by magicdawn** [comment]
我知道, 但是内测首页也太丑了...
看不下去

**Comment by magicdawn** [comment]
fixed.
