### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by qweretsd** [magicdawn/bilibili-app-recommend#110]
### 环境

Microsoft Edge
版本 126.0.2592.61 (正式版本) (64 位))
TamperMonkey
0.24.0

### 问题详细描述

为什么无法通过设置隐藏卡片里的用户名首字头像了。上一个版本还是能的？感觉有点占页面地方

### 预期结果

回调一下？

**Comment by magicdawn** [comment]
我想问一下为啥不用带头像的设置

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/d57f1a4f-07c2-4ef8-abfb-befd079c1c75)

**Comment by magicdawn** [comment]
这个我觉得太小众了, 我加了一段代码, 你要有需要可以改一下这行, 自己 build

文件 src/components/VideoCard/child-components/VideoCardBottom.tsx

https://github.com/magicdawn/bilibili-app-recommend/commit/4896fdb4008fda1a18c4f2749d7e0a2c214cbf25

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/21dd158e-b283-4339-94c5-0bfc0e7d5b80)

**Comment by qweretsd** [comment]
> 这个我觉得太小众了, 我加了一段代码, 你要有需要可以改一下这行, 自己 build
> 
> 文件 src/components/VideoCard/child-components/VideoCardBottom.tsx
> 
> [4896fdb](https://github.com/magicdawn/bilibili-app-recommend/commit/4896fdb4008fda1a18c4f2749d7e0a2c214cbf25)
> 
> ![image](https://private-user-images.githubusercontent.com/4067115/341522410-21dd158e-b283-4339-94c5-0bfc0e7d5b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzI3MDMsIm5iZiI6MTcxODkzMjQwMywicGF0aCI6Ii80MDY3MTE1LzM0MTUyMjQxMC0yMWRkMTU4ZS1iMjgzLTQzMzktOTRjNS0wYmZjMGU3ZDViODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDExMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg5NjQyN2JmMDc2Y2RjODE0NWNjYjZmNGFmYmVkYzhkYzhhMWE1ZjQ4MTVkZmFjNGQ1OTYxOTZhMDgzNWMzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KtUfr7wtQSqWj78vq2BvG-8GRUWJcfdsosmvnvS_v-0)

谢谢你那么快就回复了，但是我不知道怎么改了源码再重新build（我不知道这个是什么意思，可能是将源码导出成一个可用的js脚本文件，这一步需要做什么，我没学过，如果不是很麻烦人的话，希望能把这部分更具体一下）。我试着是否可以在浏览器里的脚本源代码里改，但是不行，加一行就运行不了脚本了。
因为之前更新之后，调用iPad api接口时，它的深夜推送很低俗？其实现在用iPad api接口推送内容是正常的，但是因为我没有ios设备，是感觉有点怪怪的。
