### ISSUE TITLE
关于图片放大脚本或插件等

### ISSUE THREAD

**Issue by HaBoomGG** [magicdawn/bilibili-app-recommend#112]
希望这个脚本可以支持一下像「浮图秀」等这种插件或脚本可以支持一下，欣赏封面很好用（点赞
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/134725695/b79489ed-cbdf-488f-a307-d0122d735c42)

**Comment by magicdawn** [comment]
感谢推荐, [这个插件](https://chromewebstore.google.com/detail/mgpdnhlllbpncjpgokgfogidhoegebod?hl=zh-CN)  挺好用的~

已修改适配. (只动了一行 css ...

**Comment by magicdawn** [comment]
v0.24.4
