### ISSUE TITLE
[Feature Request]: 从预览图位置开始播放

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#114]
像直播录像这种长视频，要是能直接打开到预览的位置就好了

不会写代码，只能分享一下想法：
下面这种预览图一大张里有100张，每张相隔8.3秒。通过预览图文件名、background-size、background-position可以知道预览的是第3大张里的第73小张，然后 `( 100 * ( 3 - 1 ) + 73 - 1 ) * 8.3` 算出预览图在2557.6秒。在链接后加上?t=2557.6打开，正是预览图所在时间。
![image](https://github.com/user-attachments/assets/b13dbc4f-ebf2-4af0-93c9-4e8d3b5858be)
![屏幕截图 2024-07-29 121401](https://github.com/user-attachments/assets/a23c42c3-b908-4fa0-bd85-b857f51998bf)
![屏幕截图 2024-07-29 121528](https://github.com/user-attachments/assets/7ae75fa1-56a4-4023-99fe-bebd9d06a21a)

**Comment by magicdawn** [comment]
设置中可以关闭
