### ISSUE TITLE
[BUG]: 有的视频从首页点进去，会跳转到中间的某个时间点。

### ISSUE THREAD

**Issue by cyd1st** [magicdawn/bilibili-app-recommend#115]
### 环境

浏览器: Edge
浏览器版本: 127.0.2651.74 
脚本管理器: TamperMonkey
脚本版本: 0.24.7

### 问题详细描述

没有找到什么规律。
有的视频点进去就会跳转到视频的某个时间点（不固定）。重新拉到开始，关闭网页，再点进去也还是一样。
频率还挺高的，点几个视频就会出现。
关闭该脚本就没复现了（需要刷新，如果不刷新还是会触发）。
最近没更新别的脚本，今天刚出现的。

**Comment by cyd1st** [comment]
发现规律了，好像和预览的进度有关。应该是昨天的[这个修改](https://github.com/magicdawn/bilibili-app-recommend/commit/158063662dc3db2bb0bc8e29bca8e8771832cad6)的问题。

**Comment by magicdawn** [comment]
![image](https://github.com/user-attachments/assets/8b6b0d84-6b4d-4cda-8854-24e2170f203f)
opt out from here

**Comment by cyd1st** [comment]
我刚发现的，可能是我不小心点到了，抱歉打扰了
