### ISSUE TITLE
[Feature]:添加分区过滤和tag关键词过滤

### ISSUE THREAD

**Issue by WsureDev** [magicdawn/bilibili-app-recommend#116]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

希望加入分区过滤和tag关键词过滤，有很多信息不会体现在标题里，有些分区真不爱看，可以直接判死刑。如果可以，希望追加如果推荐出现了命中过滤规则的视频自动反馈”我不想看“，方便养号

**Comment by magicdawn** [comment]
推荐结果无相关信息, 单独获取则是对 B站 ddos.
