### ISSUE TITLE
推荐加载不出来了

### ISSUE THREAD

**Issue by gdgoldlion** [magicdawn/bilibili-app-recommend#12]
重装，删除key，获取key，反复多次尝试均无法正确显示

显示均为一堆灰色矩形

点击查看更多，显示加载中

ToT

**Comment by gdgoldlion** [comment]
![9N`HPA0{OT0{0J ZQAF8`%A](https://user-images.githubusercontent.com/1749001/202825864-a30cf9c9-8dab-4291-a7f6-adc3692540e7.png)
![IRJPM%A3(G$T9NAU1G9T02C](https://user-images.githubusercontent.com/1749001/202825873-4c99a00f-ad81-43df-9ee5-e2edc43d1f4f.png)

**Comment by lizheyo77** [comment]
同样的问题

**Comment by magicdawn** [comment]
版本? 更新试试

![image](https://user-images.githubusercontent.com/4067115/202834944-106e309e-c847-4cf3-9431-56678d69fbfa.png)

**Comment by kayanouriko** [comment]
0.5.2版本也会提示请求出错, 请重试!!! 全屏模式没问题, 但是外面的推荐还是会偶尔刷不出来.

**Comment by gdgoldlion** [comment]
我使用了最新版本0.5.2，现在功能正常了

**Comment by magicdawn** [comment]
目前是在桌面端调用给 app 用的接口, 现在看会有一些报错, 
已经加了重试 5 次, 每次 2s 超时.
都出错就会提示. 

碰到提示, 你可以重新获取 access_key 再试.
