### ISSUE TITLE
全屏模式往下滚动后出现水平滚动条

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#120]
`.css-5oc4n1` 里的 `padding-inline: calc(-50% + 50vw)`  禁用后，能看到是因为 `margin-inline: calc(50% - 50vw)` 让内容延伸到了垂直滚动条下，导致横向滚动条出现。我把 `margin-inline: calc(50% - 50vw)` 改成 `margin-inline: calc(50% - 50vw + 8px)`，横向滚动条就消失了

**Comment by magicdawn** [comment]
什么平台, 截下图

macOS Chrome 未复现
