### ISSUE TITLE
[BUG]:脚本失效了

### ISSUE THREAD

**Issue by singularity2000** [magicdawn/bilibili-app-recommend#124]
### 环境

浏览器: Chrome
浏览器版本: 129.0.6668.101、130.0.6723.59
脚本管理器: TamperMonkey篡改猴测试版
脚本版本: v0.25.0.0 、v0.25.0.1-g726ca0b

### 问题详细描述

B站首页切换“推荐”、“动态”、“收藏”等标签无反应，功能失效。
升级浏览器、删除并重新获取access key、刷新网页、更新脚本到最新测试版……等方法都无效。

### 预期结果

直到几个小时前，功能都是正常的，现在忽然发现不行了。

**Comment by singularity2000** [comment]
我有两台笔记本，登着同一个谷歌账号，Chrome插件、油猴脚本都走的浏览器同步。结果今天发现，另一台电脑上脚本功能正常。脚本坏掉的那台电脑，脚本我彻底删除+重装很多次了，就是加载不出来推流，不知道为什么。还没测试删除油猴插件，因为脚本很多。

**Comment by magicdawn** [comment]
![image](https://github.com/user-attachments/assets/96459251-b216-4b4e-98c8-2a161ba60449)

![image](https://github.com/user-attachments/assets/fc716b34-5f87-41a0-8751-726260a3bb40)

1. 可以用这个备份
2. 恢复是点下边那个按钮~

但是 access_key 不会同步

**Comment by singularity2000** [comment]
感谢，这个方法我昨晚上试过了，脚本坏掉的那台电脑，重新安装脚本后，无论是使用默认配置、还是恢复保存在笔记草稿的自定义配置，推送界面要么只显示B站默认的推送，要么一片空白，只有个“加载中”字样。

**Comment by singularity2000** [comment]
如图所示 @magicdawn 
![image](https://github.com/user-attachments/assets/c7bbce77-061c-4d92-990d-ac712c282563)

**Comment by singularity2000** [comment]
找出罪魁祸首了，是一个百度网盘的解析脚本（https://1.94.138.197/bangumi），近日突然更新了对B站视频的下载解析，但是网络连接的稳定性又没弄好，还与 bilibili-app-recommend 发生冲突。禁止其在B站生效后问题解决，打扰作者了！
![image](https://github.com/user-attachments/assets/bc669f7f-3517-4e0b-8185-5ccc4d067ae8)
