### ISSUE TITLE
[BUG]:点击换一换就会显示出错，重新获取access key也没用

### ISSUE THREAD

**Issue by SwolleSphincter** [magicdawn/bilibili-app-recommend#127]
### 环境

浏览器: Chrome
浏览器版本: 130.0.6723.70 最新
脚本管理器: TamperMonkey Beta
脚本版本: v0.25.1 最新
![Screenshot 2024-10-23 204325](https://github.com/user-attachments/assets/23dd854a-d883-42b3-a156-b6ef88464487)

### 问题详细描述

如题，刷新后就会显示出错，浏览器版本和脚本版本都是最新的，重新获取access key后刷新一两次又会再次报错，把脚本排到第一个没用，重装脚本也没用，关闭其他所有脚本也没用。电脑推荐正常，切回手机端推荐什么都加载不出来之后会报错，望修复

**Comment by magicdawn** [comment]
亲测没问题哈~还是要你自己排查...

之前有些用户在 greaskfork 提到了 隐私獾 https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/253395

你可以看看有没有装类似的插件/脚本

**Comment by SwolleSphincter** [comment]
> 亲测没问题哈~还是要你自己排查...
> 
> 之前有些用户在 greaskfork 提到了 隐私獾 https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/253395
> 
> 你可以看看有没有装类似的插件/脚本

我关闭了除了油猴以外的所有扩展程序以及油猴包含的其他所有的插件，可惜问题依然存在。不过我删掉access key之后就能正常刷新了，不知道是不是access key的问题

**Comment by SwolleSphincter** [comment]
> > 删掉access key之后就能正常
> 
> 删掉之后用 app 推荐就是相当于游客匿名了~
> 
> 听你的描述应该是有报错, 截一下图吧. 右键-检查-切到 console (中文: 控制台)

您好，我重新获取access key刷了一下，我不太懂这方面，如果截错了请告诉我
![Screenshot 2024-10-24 073959](https://github.com/user-attachments/assets/077361a4-a2c2-4982-ab5d-e21effeff854)
![Screenshot 2024-10-24 074150](https://github.com/user-attachments/assets/7789d7e2-13ec-4fbe-9ac9-9a82b6a62e25)

**Comment by magicdawn** [comment]
看起来像全部超时, 写死的2秒...
我在开发版调大了这个超时(20秒), 你可以安装试一下
https://github.com/magicdawn/bilibili-app-recommend/raw/release-nightly/bilibili-app-recommend.mini.user.js

**Comment by SwolleSphincter** [comment]
> 看起来像全部超时, 写死的2秒... 我在开发版调大了这个超时(20秒), 你可以安装试一下 https://github.com/magicdawn/bilibili-app-recommend/raw/release-nightly/bilibili-app-recommend.mini.user.js

已经解决了，谢谢大佬
