### ISSUE TITLE
获取 access_key 后无法刷新

### ISSUE THREAD

**Issue by JoeScandium** [magicdawn/bilibili-app-recommend#13]
会出现如图所示的提示
![image](https://user-images.githubusercontent.com/40695113/206355994-e92b9a84-41fb-4174-9dc6-7fbda7cddc45.png)
如果删除后刷新就是下图所示正常的随机推荐，重新获取 access_key 的话还是上图所示
![image](https://user-images.githubusercontent.com/40695113/206356444-a2371bfd-b985-4e04-acd8-7847bba45c40.png)

Windows 11 专业版 22H2 22621.819
Chrome 108.0.5359.99 （64 位）
TamperMonkey v4.18.1

**Comment by magicdawn** [comment]
see #16
