### ISSUE TITLE
在悬停于弹幕栏时存在数据框情况

### ISSUE THREAD

**Issue by Amber-niux** [magicdawn/bilibili-app-recommend#130]
**环境**：
浏览器：edge
浏览器版本：130.0.2849.56 (正式版本) (64 位)
脚本管理器：Tampermonkey
脚本管理器版本：v5.1.1
**问题详细描述：**
在使用中已经关闭其他脚本以便排查。不仅仅存在于B站使用，在web使用中都存在此问题，Google搜索无果特来请教。
<img width="903" alt="屏幕截图 2024-10-30 203842" src="https://github.com/user-attachments/assets/5eaeb00a-e005-43a4-9c92-df6790fa5fea">

<img width="699" alt="屏幕截图 2024-10-30 203947" src="https://github.com/user-attachments/assets/a2501d16-ec07-432f-a1b4-b1f3227f5a86">

**Comment by magicdawn** [comment]
这是电脑卡柱了吧......

**Comment by Amber-niux** [comment]
已经解决了，谢谢up的脚本。很好用。> 这是电脑卡柱了吧......
