### ISSUE TITLE
[BUG]:手机端推荐视频一直显示出错了，请刷新重试

### ISSUE THREAD

**Issue by AkikoAkaki** [magicdawn/bilibili-app-recommend#131]
### 环境

浏览器: Chrome
浏览器版本: 130.0.6723.92
脚本管理器: TamperMonkey
脚本版本: 0.24.8

### 问题详细描述

![image](https://github.com/user-attachments/assets/a792e7e1-83e1-4c24-b19a-1af8d2172659)

无法显示手机端推荐，只显示刷新重试，重新获取access key也没有作用

**Comment by magicdawn** [comment]
更新到最新 v0.25.3 试试，已经处理过类似问题，好像是app端推荐 API 超时导致，已由 2s 改为 20s

**Comment by AkikoAkaki** [comment]
> 更新到最新 v0.25.3 试试，已经处理过类似问题，好像是app端推荐 API 超时导致，已由 2s 改为 20s

感谢，已解决
