### ISSUE TITLE
[BUG]:换一换按钮位置到屏幕左侧

### ISSUE THREAD

**Issue by woyaobaidalan** [magicdawn/bilibili-app-recommend#132]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

![Snipaste_2024-11-04_16-46-14](https://github.com/user-attachments/assets/78d9898b-de79-4541-826e-ca17e45d09bc)
老哥，这是正常的吗？还是说我这边的问题。感觉不如在右侧方便

**Comment by magicdawn** [comment]
> 老哥，这是正常的吗？还是说我这边的问题。感觉不如在右侧方便

什么设备, 这明显是右边放不下去了么...

正常应该是这样
![bili](https://github.com/user-attachments/assets/92bdb303-8071-46f6-9f89-aca9f0b3080f)

**Comment by wdwddog** [comment]
![a7ae95bc-0405-4139-847d-7b8b27939d63](https://github.com/user-attachments/assets/6414086e-aca0-47fb-a5bf-bb3e445a3aad)
一样,360急速浏览器

**Comment by magicdawn** [comment]
chrome / edge / firefox PLZ!

**Comment by woyaobaidalan** [comment]
我昨天还是好着的，但不知道为什么，今天一看发现变成这样了，过来问问。一会我再去看看什么原因

**Comment by magicdawn** [comment]
没更新啊
![image](https://github.com/user-attachments/assets/23e3ed84-2bf4-46a4-826b-2356d24eafc5)

什么版本
![image](https://github.com/user-attachments/assets/95212d72-53ed-4a0d-aaf9-438c67a3610e)
这是让填的...括号里的如 是举例说明...

**Comment by woyaobaidalan** [comment]
浏览器：Chrome
浏览器版本： 130.0.6723.92（正式版本） （64 位）
脚本管理器：TamperMonkey
脚本版本：v0.25.3

**Comment by Z-Su-ne** [comment]
![image](https://github.com/user-attachments/assets/836954e8-5223-42ff-9626-c0d55a1969bf)
全屏是这个样子的，出去一下就变成了这样

浏览器：Microsoft Edge
浏览器版本：130.0.2849.68 (正式版本) (64 位)
脚本管理器：Tampermonkey
脚本管理器版本：5.1.1
脚本版本：0.25.3

**Comment by magicdawn** [comment]
这个当时开发的时候用了 B 站自带的样式, 现在 B 站把这个删了...

v0.25.4 已 fix.

-----

类似的情况之前发生过 #66 #67 #68 ...
