### ISSUE TITLE
[BUG]:油猴脚本开关会自动关闭，每次都要重新打开，且每次更新脚本后版本还会自动回退到v0.24.13

### ISSUE THREAD

**Issue by biafn** [magicdawn/bilibili-app-recommend#133]
### 环境

浏览器: edge
脚本管理器: 暴力猴

### 问题详细描述

油猴脚本开关会自动关闭，每次都要重新打开，且每次更新脚本后版本还会自动回退到v0.24.13

**Comment by magicdawn** [comment]
请自查 脚本管理器 同步相关设置.
