### ISSUE TITLE
[BUG]:请在动态tab中去除直播内容

### ISSUE THREAD

**Issue by yinzhefuyun** [magicdawn/bilibili-app-recommend#134]
### 环境

浏览器: Chrome
浏览器版本: 130
脚本管理器:  TamperMonkey
脚本版本: 0.26.0

### 问题详细描述

点开动态tab

### 预期结果

动态tab中去没有直播内容

**Comment by magicdawn** [comment]
![image](https://github.com/user-attachments/assets/50357473-fe2c-48b6-b9e3-ade72f796978)
