### ISSUE TITLE
和脚本‘bilibili不新开标签页直接在当前页面打开’ 冲突，希望添加此功能

### ISSUE THREAD

**Issue by JimmieSteve** [magicdawn/bilibili-app-recommend#135]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

同时开启此脚本 和 ‘bilibili不新开标签页直接在当前页面打开’，‘bilibili不新开标签页直接在当前页面打开’ 失效

### 预期结果

b站每点击一个视频就新开一个标签页很别扭，内存占用也很高，希望合并这个功能

**Comment by magicdawn** [comment]
在当前标签页打开会导致丢失当前页状态...省那么点内存, 基本没有使用体验
所以暂不考虑

**Comment by JimmieSteve** [comment]
在macOS 使用 add to dock 功能将b站转化为应用之后，每次打开一个b站链接视频并不是新开一个标签页，而是在后台新开一个b站浏览器窗口，所以多看几个视频如果不是每一次都手动关闭的话，后台会有一堆b站窗口

**Comment by magicdawn** [comment]
下个版本在这个加一个

![image](https://github.com/user-attachments/assets/010c3a4b-22ef-475d-9585-72e7afb00d0e)

当前页打开

**Comment by magicdawn** [comment]
v0.26.1 已添加, 但从详情页返回推荐又会重新刷新...

你可以试试 [BewlyBewly](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp) 的抽屉打开, 好像在这个安装成应用的场景比较好用

**Comment by JimmieSteve** [comment]
刚刚更新使用了一下，首页推荐信息流确实是在当前页面打开的，使用体验正常，要是想返回主页就点左上角的b站logo，一切正常，不会新开标签页。但是点击收藏，历史等 都是新开一个标签页，我原本用的‘bilibili不新开标签页直接在当前页面打开’点击任何链接都是当前页面打开，不会出现这样的情况，希望作者参考(https://greasyfork.org/zh-CN/scripts/389127-bilibili超链接不新开标签页直接在当前页面打开) ，你提到的bewlybewly 只在chrome edge端开发，并没有在safari端，一般封装成应用都是使用safari add to dock功能。最后感谢回复以及开发。

**Comment by magicdawn** [comment]
1. chrome 也是有的 (edge 类似)

![image](https://github.com/user-attachments/assets/5025fbc3-a6f4-48da-a69d-1752205765e9)

**Comment by JimmieSteve** [comment]
<img width="332" alt="image" src="https://github.com/user-attachments/assets/b88e46ad-04c1-43d9-9441-cd6d648c0c62">
确实有 不过就是不太美观哈哈

**Comment by JimmieSteve** [comment]
希望作者能完善一下，让每一个b站窗口链接都在当前标签下打开，现在还有许多链接会新开一个标签页

**Comment by magicdawn** [comment]
开发版 https://github.com/magicdawn/bilibili-app-recommend/raw/release-nightly/bilibili-app-recommend.mini.user.js

此脚本只处理脚本生成的链接, 顶栏上的动态/收藏/历史等搭配 https://greasyfork.org/zh-CN/scripts/389127 使用
