### ISSUE TITLE
新版本脚本功能失效

### ISSUE THREAD

**Issue by wuyi2333** [magicdawn/bilibili-app-recommend#136]
### 环境

浏览器: edge 
浏览器版本:130.0.2849.80 
脚本管理器: ( TamperMonkey)
脚本版本: 0.26.2/ 0.26.1

### 问题详细描述

功能失效，首页不能正确显示原本的推荐了，变回了没有脚本的样子

**Comment by magicdawn** [comment]
macOS 下同环境(edge v130.0.2849.80 (正式版本) (arm64), 篡改猴 v5.3.2, 脚本 v0.26.2) 无法复现.

查下有没有冲突 或 控制台报错吧

**Comment by Holowila** [comment]
同edge  脚步失效解决
edge版本130.0.2849.80
脚本版本: 0.26.2

解决办法：到edge扩展管理中打开开发人员模式
