### ISSUE TITLE
无法刷新了

### ISSUE THREAD

**Issue by gdgoldlion** [magicdawn/bilibili-app-recommend#14]
-------------------------------------------------
请求出错, 已重试5次:
  1) 鉴权失败，请联系账号组
  2) 鉴权失败，请联系账号组
  3) 鉴权失败，请联系账号组
  4) 鉴权失败，请联系账号组
  5) 鉴权失败，请联系账号组

请重新获取 access_key 后重试~
-------------------------------------------------

多次尝试后，都是这个结果

**Comment by magicdawn** [comment]
see #16
