### ISSUE TITLE
鉴权失败，请联系账号组 code -663 问题

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/bilibili-app-recommend#16]
# 同类问题请在此处反馈.

![image](https://user-images.githubusercontent.com/40695113/206355994-e92b9a84-41fb-4174-9dc6-7fbda7cddc45.png)

如 https://github.com/magicdawn/bilibili-app-recommend/issues/12#issuecomment-1321401768 所说

> 目前是在桌面端调用给 app 用的接口, 现在看会有一些报错,
> 已经加了重试 5 次, 每次 2s 超时.
> 都出错就会提示.
> 碰到提示, 你可以重新获取 access_key 再试.

## 尝试解决

打开设置面板, 把 "推荐接口使用并行请求" 选项去掉. 

![image](https://user-images.githubusercontent.com/4067115/206513844-7c094b05-a948-4841-8cbb-eae611e58c49.png)

**Comment by kayanouriko** [comment]
Windows 环境下没问题了, macOS 环境下依旧提示截图的报错, 我的配置除了系统不一样, 别的都一样的.

macOS Ventura 13.0.1
Chrome 108.0.5359.98
Tampermonkey 4.18.1
脚本 0.6.6

**Comment by magicdawn** [comment]
> 无法滑到设置面板的高级选项，只显示了Auth和开关 ![image](https://user-images.githubusercontent.com/40695113/206609753-85b751d3-0085-421a-b0d6-b4e361ba602e.png)

更新一下

**Comment by JoeScandium** [comment]
Windows 环境下还是出现一样的问题，把 "推荐接口使用并行请求" 选项去掉没有改变什么

**Comment by dd178** [comment]
更新了，选项也去掉了，问题未解决

**Comment by CHAOS-mnt** [comment]
Windows 10 企业版 21H1
Chrome版本 108.0.5359.99
TamperMonkey v4.18.1
脚本 0.6.6
也是前两天开始出现问题，一开始是多刷新几次还有概率刷出来，现在已经彻底刷不出来了，不带access_key可以正常返回随机推荐内容。推荐接口使用并行内容开和关都是一样

**Comment by magicdawn** [comment]
same issue https://github.com/indefined/UserScripts/issues/114

**Comment by ashuang001** [comment]
照着做了，问题依旧。

**Comment by L1nwz1** [comment]
现在还是同样的问题

**Comment by magicdawn** [comment]
## v0.7.0 2022-12-14

老接口挂了, 完全不可用状态, 换上了 PC 首页推荐接口

- 不需要 access_key 了
- 标记不喜欢功能没了, 新接口下做不了
- 和首页自带推荐一样, 使用 BVID
- 和首页自带推荐不一样, 自带推荐有视频预览 / 弹幕预览, 本项目还是鼠标滑动查看快照图片.
- 首页自带推荐的接口, 貌似不会给你推荐番剧 (没有看见数据, 所以没有兼容)
- 老代码只注释了, 所以有点乱, 先用着吧~~~

**Comment by ashuang001** [comment]
0.7版本能用了。赞美作者。

**Comment by yinzhefuyun** [comment]
> ## v0.7.0 2022-12-14
> 老接口挂了, 完全不可用状态, 换上了 PC 首页推荐接口
> 
> * 不需要 access_key 了
> * 标记不喜欢功能没了, 新接口下做不了
> * 和首页自带推荐一样, 使用 BVID
> * 和首页自带推荐不一样, 自带推荐有视频预览 / 弹幕预览, 本项目还是鼠标滑动查看快照图片.
> * 首页自带推荐的接口, 貌似不会给你推荐番剧 (没有看见数据, 所以没有兼容)
> * 老代码只注释了, 所以有点乱, 先用着吧~~~

https://github.com/indefined/UserScripts/issues/114  原版的作者好像修复了，需要再发两个参数

**Comment by gdgoldlion** [comment]
> > ## v0.7.0 2022-12-14
> > 老接口挂了, 完全不可用状态, 换上了 PC 首页推荐接口
> > 
> > * 不需要 access_key 了
> > * 标记不喜欢功能没了, 新接口下做不了
> > * 和首页自带推荐一样, 使用 BVID
> > * 和首页自带推荐不一样, 自带推荐有视频预览 / 弹幕预览, 本项目还是鼠标滑动查看快照图片.
> > * 首页自带推荐的接口, 貌似不会给你推荐番剧 (没有看见数据, 所以没有兼容)
> > * 老代码只注释了, 所以有点乱, 先用着吧~~~
> 
> [indefined/UserScripts#114](https://github.com/indefined/UserScripts/issues/114) 原版的作者好像修复了，需要再发两个参数

这个PC 首页推荐接口，就是网页版置顶的那个推荐，而不是access_key 的推荐
网页版置顶推荐的质量比较差，access_key 的精准度比较高，内容也新
只能先凑合了

**Comment by magicdawn** [comment]
v0.8.0 已支持接口切换.
设置-开关-使用桌面端接口, 默认使用 App 端接口, 可自由切换.
