### ISSUE TITLE
可以用现在APP使用的接口，不必换到PC首页推荐接口

### ISSUE THREAD

**Issue by Myitian** [magicdawn/bilibili-app-recommend#18]
https://github.com/magicdawn/bilibili-app-recommend/blob/27d8fce905b1d3f54a84abd4c6a4afdf25f64fb9/CHANGELOG.md?plain=1#L3-L5

可以用现在APP使用的接口 `https://app.bilibili.com/x/v2/feed/index`，不必换到PC首页推荐接口
仅需`appkey`和`access_key`就可以获取内容
如`https://app.bilibili.com/x/v2/feed/index?appkey=27eb53fc9058f8c3&access_key=********************************`
响应内容包含稍候再看/不喜欢/反馈等

返回示例：
https://paste.ubuntu.com/p/nSFt4yjFRf/
美化输出：
https://paste.ubuntu.com/p/3yZ8TNfJcs/

**Comment by magicdawn** [comment]
v0.8.0 已支持接口切换.
设置-开关-使用桌面端接口, 默认使用 App 端接口, 可自由切换.

**Comment by magicdawn** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/168
这个还没加上, 你是在哪抓的么?

**Comment by Myitian** [comment]
在用APP的时候自己抓的

Tao ***@***.***> 于2023年5月30日周二 21:17写道：
