### ISSUE TITLE
无法显示推荐模块

### ISSUE THREAD

**Issue by pickalexrener** [magicdawn/bilibili-app-recommend#2]
版本：0.0.8
chrome版本：101.0.4951.67
Tampermonkey版本：4.16.1
控制台报错：[bilibili-app-recommend]: init fail
(anonymous) @ userscript.html?name=bilibili-app-recommend.user.js&id=1aefc93f-c841-4eb1-95e6-185a1a4527ff:343

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/170535025-bf6cbec6-3671-4fca-84ef-b68beefba32a.png)

这里有 "回到旧版" 按钮的是新版本
