### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by xlzy520** [magicdawn/bilibili-app-recommend#22]
boss.hdslb.com/videoshotpvhdboss/561192325_79a08b-0001.jpg

请问这个链接是怎么生成的

**Comment by magicdawn** [comment]
有个接口可以取到

https://github.com/magicdawn/bilibili-app-recommend/blob/v0.10.1/src/components/VideoCard/card.service.ts#L7-L16

参考 https://github.com/indefined/UserScripts/tree/master/bilibiliHome 的代码
