### ISSUE TITLE
能不能根据播放量和点赞数做一下过滤

### ISSUE THREAD

**Issue by none2003** [magicdawn/bilibili-app-recommend#24]
B赞经常回莫名其妙的推荐一些播放量很高，但是点赞比例很低的低质视频，比如某音搬运过来的搞笑视频之类的，挺浪费时间的，希望能有配置项对于满足条件的视频进行过滤，默认不开启，开启后根据这两项配置进行过滤：
1. 过滤XX播放量以下的视频（XX是数字，比如10000）
2. 过滤点赞比例（点赞数量/播放量）低于XX.XX%的视频（XX.XX是数字，保留两位小数，比如，0.15%）

**Comment by magicdawn** [comment]
可以使用「我不想看」功能调教推荐系统.

**Comment by magicdawn** [comment]
v0.10.2 可以按照播放量 / 视频时长过滤.
点赞数据在 app 端推荐接口中取不到, 不做支持.

**Comment by none2003** [comment]
之前B站还在使用老界面的时候用的是下面这个脚本，当时看到是有“赞”的数据的，鼠标放到缩略图上还会滚动一些弹幕。

https://github.com/indefined/UserScripts/blob/master/bilibiliHome/bilibiliHome.user.js

其中309行的data.like属性看着是赞的数量，1355-1427行貌似是加载了弹幕。
