### ISSUE TITLE
推荐栏不会消失，不确定是不是bug及建议

### ISSUE THREAD

**Issue by lmpker** [magicdawn/bilibili-app-recommend#25]
1. 红色这行不会消失，还是有点影响体验，不知道是我个人设置问题，还是都是这样。
2. 实际来讲，这行有用信息就【设置】和【换一换】，感觉做一个按钮放在左边最好，右边也行。
3. 像Bilibili Evolved那样，做一个灰色图标，既不影响正常浏览，用到的时候也方便找（左边的空闲区域还挺多的）

![微信截图_20230417174452](https://user-images.githubusercontent.com/9392663/232453361-6fcc317c-2f78-4b6b-9c63-301da0682a7b.png)

**Comment by magicdawn** [comment]
正常应该是这样
![image](https://user-images.githubusercontent.com/4067115/232459622-c8041de6-3496-4498-837d-dc2a94bf576d.png)

你是不是没开全局固定?

![image](https://user-images.githubusercontent.com/4067115/232459766-182ce930-349b-4789-a738-e45608a968a8.png)


还有高度需要是默认的 50, 不支持其他定制.
或者禁用 Envolved, 这个脚本与自带标题栏也是兼容的

**Comment by lmpker** [comment]
好嘞，我去试下，谢谢
