### ISSUE TITLE
希望可以添加根据视频日期范围进行过滤的功能

### ISSUE THREAD

**Issue by MuYuehe** [magicdawn/bilibili-app-recommend#28]
希望能看到近期发布的视频,而不是几个月前甚至几年前的视频

**Comment by magicdawn** [comment]
TLDR: 做不到 & 不想做.

1. 目前推荐接口不支持.
2. 桌面端接口推荐结果有日期, App 端接口取不到日期.
3. 日期应该不影响视频质量 :)
