### ISSUE TITLE
不支持safari

### ISSUE THREAD

**Issue by ulongcha** [magicdawn/bilibili-app-recommend#29]
safari使用Tampermonkey安装脚本后进入bilibili主页推荐部分加载失败
<img width="1358" alt="截屏2023-05-26 16 50 24" src="https://github.com/magicdawn/bilibili-app-recommend/assets/50707687/3c8be2b0-ee0d-4277-975c-278e52e6c18e">

**Comment by magicdawn** [comment]
不支持 safari.
