### ISSUE TITLE
或许可以在脚本栏(比如在暴力猴插件按钮里面)添加一个切换全推荐模式的按钮

### ISSUE THREAD

**Issue by ydivho12123** [magicdawn/bilibili-app-recommend#3]
每次点开首页都得点击查看更多有点麻烦其实.或许可以添加一种把首页全部更换成推荐的模式
比如像这个 https://greasyfork.org/zh-CN/scripts/436341-b%E7%AB%99%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90%E7%BA%AF%E4%BA%AB%E7%89%88
但这个没有点击添加稍后再看的按钮,要是可以首页全屏推荐同时可以点击视频稍后再看就完美了

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/173531554-5392166c-4ee6-4af7-9b94-a2d387731a0c.png)


![image](https://user-images.githubusercontent.com/4067115/173531431-05c5e5aa-92e4-435c-ba40-07607b644740.png)

已更新 v0.3.3

**Comment by kayanouriko** [comment]
刚想发 issue 发现有人提了, 作者真的不考虑一下吗?
我感觉入侵性并不强, 安装此脚本基本是想和 app 一样首页当推荐无限浏览的.
目前是可以打开自动全屏, 但是 UI 层面感觉不想在使用 b 站, 而是单独出来的一个界面, 逛完推荐有时候想点其他例如动态, 收藏等等的时候需要手动关闭. 想说的意思是使用体验上比较割裂, 不流畅.
这脚本功能是做的最好的, 我看了一下脚本那边也有反馈, 真的希望作者可以加一个首页全屏模式.

**Comment by magicdawn** [comment]
就是做一个纯享版, 我明白了
