### ISSUE TITLE
分类栏bug

### ISSUE THREAD

**Issue by MilkSC** [magicdawn/bilibili-app-recommend#30]
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/99065905/f1263660-7d91-4976-a96c-73cf16ede564)
然后我写了个插件，去除这个bug栏：
https://greasyfork.org/zh-CN/scripts/466238-bilibili-app-recommend补丁

**Comment by magicdawn** [comment]
内测模式首页 + SectionRecommend(两行推荐, 即没开纯推荐模式下), 特有问题.
fixed in v0.11.6
