### ISSUE TITLE
[BUG]:无法使用 backspace 调出不感兴趣的按钮 x

### ISSUE THREAD

**Issue by songdixp** [magicdawn/bilibili-app-recommend#33]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)

### 问题详细描述

我的电脑 ： macbook  pro 16寸 m1pro 芯片，按 backspace按钮，刷新页面，无法调用出x不感兴趣的按钮。不清楚为什么，其他的快捷按键都有效

**Comment by magicdawn** [comment]
需要方向键选中视频，选中的视频有边框标识，而且该视频支持提交不喜欢(左上角有❌按钮：即使用 APP 端API 获取的推荐视频 + 已获取access_key

**Comment by songdixp** [comment]
谢谢，使用App端api 然后获取access_key 再按backspace 就有了
