### ISSUE TITLE
在切换到已关注时，可能会被困住

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#34]
### 环境

浏览器: Edge
浏览器版本: 114.0.1823.37
脚本管理器: TamperMonkey

### 问题详细描述

切换到已关注时，加载需要很长时间。因为加载过程中那几个按钮会灰掉不可用，期间无法切换到其它，会被困在已关注

### 预期结果

希望可以切换的按钮不会灰掉，允许放弃加载切换到其它

**Comment by magicdawn** [comment]
有意为之.

**Comment by magicdawn** [comment]
代码写起来简单!

**Comment by magicdawn** [comment]
慢么? 
bilibili-app-recommend:components:RecGrid refresh cost 1596 ms +2s
我这只要 1.6 秒啊

**Comment by magicdawn** [comment]
1.控制台执行 
```
localStorage.debug = 'bilibili-app-recommend:components:RecGrid'
```

2.刷新
查看控制台输出, 可以看到具体信息
