### ISSUE TITLE
[BUG]: 0.12.4版本字体变了

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#35]
### 环境

浏览器: Edge
浏览器版本: 114.0.1823.37
脚本管理器: TamperMonkey

### 问题详细描述

![屏幕截图(3)](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/8d8df205-e26e-4128-8a69-987162bfae18)
左边是0.12.4，右边是0.12.3（B站默认字体）

### 预期结果

保持默认字体

**Comment by magicdawn** [comment]
v0.12.5 已修复
