### ISSUE TITLE
[BUG]:切换为电脑端推荐后，未能保存为电脑端推荐的状态，导致每次都得手动切换

### ISSUE THREAD

**Issue by bling-yshs** [magicdawn/bilibili-app-recommend#39]
### 环境

浏览器: Chromium 102.0.5005.167
脚本管理器: ScriptCat

### 问题详细描述

1. 打开bilibili
2. 切换为电脑端推荐
![Snipaste_2023-06-16_09-41-51](https://github.com/magicdawn/bilibili-app-recommend/assets/41812674/3048f559-5c3d-453a-8398-64007a2b5b56)
3. 刷新网页
4. 又变成了app端推荐
![Snipaste_2023-06-16_09-39-29](https://github.com/magicdawn/bilibili-app-recommend/assets/41812674/26de53cf-ca56-49ef-b541-fd2d1d15ffae)

**Comment by magicdawn** [comment]
为了兼容 macOS Safari https://github.com/quoid/userscripts, 全部 API 都改成了 `GM.`
而 Scriptcat 不支持支持面最广的 `GM.` API.

所以: 不支持 Scriptcat, 装一个 tampermonkey 或 violentmonkey 吧.

**Comment by magicdawn** [comment]
UPDATE: 不是不支持 `GM.` API, 看起来是不能持久化, 不知为何.

**Comment by bling-yshs** [comment]
噢，确实是因为script cat的GM api不太一样，换其他脚本管理器确实没有问题了
