### ISSUE TITLE
key获取不了

### ISSUE THREAD

**Issue by windyhun** [magicdawn/bilibili-app-recommend#4]
如题，账号已经登录了

**Comment by Rimliya** [comment]
我也

**Comment by magicdawn** [comment]
谁按照这个步骤试一下

1.确保自己是登录状态

2.访问 https://passport.bilibili.com/login/app/third?appkey=27eb53fc9058f8c3&api=https:%2F%2Fwww.mcbbs.net%2Ftemplate%2Fmcbbs%2Fimage%2Fspecial_photo_bg.png&sign=04224646d1fea004e79606d3b038c84a

3.得到一个 json 数据
![image](https://user-images.githubusercontent.com/4067115/181436986-f44f6c92-ec15-464f-838c-98095a8d2904.png)

4.访问数据里面的 `confirm_uri`, 会重定向到 `https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png?access_key=xxx`

![image](https://user-images.githubusercontent.com/4067115/181437614-22dd799b-95a5-4c81-b275-1f54696ceb5f.png)


这就是期望的 access_key, 获取不了的照这个流程试一下, 有不一样的贴出来.
注意 (access_key 和 confirm_uri) 为个人隐私,不要泄露 ...

**Comment by JoeScandium** [comment]
> 
获取授权超时，按照上面步骤我最后定向到这样的网址
https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png?access_key=xxx&mid=xxx&uname=xxx&sign=xxx

**Comment by magicdawn** [comment]
TamperMonkey `@match` 问题. https://github.com/Tampermonkey/tampermonkey/issues/1560

更新到 v0.4.1 已兼容. https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend
