### ISSUE TITLE
[BUG]: 稍后观看会卡死页面

### ISSUE THREAD

**Issue by izhangxm** [magicdawn/bilibili-app-recommend#41]
### 环境

浏览器: Microsoft Edge
浏览器版本: 114.0.1823.51 (正式版本) (arm64)
脚本管理器: TamperMonkey
操作系统：macOS Ventra 13.4
其他：已退出所有科学软件和各种广告拦截器

### 问题详细描述

切换到稍后观看就直接卡死了，打开调试清除各种存贮和数据后，重新登录，依然会首先来到稍后观看这个tab，然后接着卡死

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/16874796/fad416ef-8e22-494c-81ab-2837df10e969)

### 预期结果

页面会卡死，无法使用

**Comment by magicdawn** [comment]
脚本版本呢

**Comment by magicdawn** [comment]
确认下用的是最新版本

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/0cd00d26-5a09-4c0d-bb0f-65d05d5b268b)

**Comment by magicdawn** [comment]
看下 debug log

1.设置 
localStorage.debug = 'bilibili-app-recommend:*'

也可以用 devtools 设置
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/7234deb4-fb2a-4cf8-ad0b-7e41a5cb7158)

2.刷新
截一下控制台, 注意把 详细 这个级别勾上

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/6cb8e2da-4a65-4d95-85b6-b0f11c0351a8)

**Comment by magicdawn** [comment]
BTW: 删除这行可以返回默认的 Tab, 也可以重置成默认设置


![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/1732acb4-18e4-4c59-b76e-ac06ba91903e)

**Comment by magicdawn** [comment]
那你还卡么?

**Comment by magicdawn** [comment]
需要控制台执行一下这句

```js
localStorage.debug = 'bilibili-app-recommend:*'
```

然后刷新, 就可以看到输出了.

**Comment by Snowballl11** [comment]
油猴管理面板中选中脚本再恢复到出厂状态可解决
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/69752299/bb81b250-f16d-49e5-9ada-75d2459e6e06)

**Comment by magicdawn** [comment]
你们稍候再看数量是不是很少, 比如10几个视频, 不足一屏~

---------

感谢 @izhangxm 反馈日志, 问题已定位, 马上发 v0.14.5

**Comment by magicdawn** [comment]
已经发布了!

**Comment by magicdawn** [comment]
greasyfork 有时候看着是 "更新到 v0.14.5", 给的版本还是 v0.14.4

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/2197a2f2-0df7-4e72-8950-7045c1a049ab)

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/36fcdd1f-8c3f-440e-98b0-51bbc2c73a89)

它时有一定的缓存时间, 可以

1.等他更新
2.或者使用 GitHub 安装, https://github.com/magicdawn/bilibili-app-recommend/raw/release/bilibili-app-recommend.mini.user.js
