### ISSUE TITLE
更新到最新版本，点到稍后再看之后就会卡住

### ISSUE THREAD

**Issue by Mikasalzc** [magicdawn/bilibili-app-recommend#42]
![Snipaste_2023-06-18_22-00-55](https://github.com/magicdawn/bilibili-app-recommend/assets/78862120/0c6b4756-75e4-4f18-9a61-17b66d3ebaae)

**Comment by magicdawn** [comment]
greasyfork 有时候看着是 "更新到 v0.14.5", 给的版本还是 v0.14.4

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/2197a2f2-0df7-4e72-8950-7045c1a049ab)

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/36fcdd1f-8c3f-440e-98b0-51bbc2c73a89)

它时有一定的缓存时间, 可以

1.等他更新
2.或者使用 GitHub 安装, https://github.com/magicdawn/bilibili-app-recommend/raw/release/bilibili-app-recommend.mini.user.js

**Comment by magicdawn** [comment]
检查版本, 应该是没更新成功.

**Comment by magicdawn** [comment]
看一下 #41, 在 v0.14.5 已经修复.
