### ISSUE TITLE
feature: 自定义宽屏页面的列数为4

### ISSUE THREAD

**Issue by izhangxm** [magicdawn/bilibili-app-recommend#43]
首先感谢作者大大的辛苦付出，让我们用上了这么好用的插件，推荐的视频明显有了很大的改善。

我本人使用的14寸的macbook，5列的视频数量说实话有点儿密集，刚开始我还没发现是怎么回事，心想同样是滑动页面，眼睛咋就跟不上内容了呢？总觉得太快。后来看到Youtube才发现原因 油管是4列的 图比较大。于是我使用stylish插件，修改css，将grad改成4列。

呼～终于舒服了！下面是预览图

<img width="1723" alt="image" src="https://github.com/magicdawn/bilibili-app-recommend/assets/16874796/42c8f5f8-5832-4df3-96dd-8bf1f6ded7c7">

不知道作者能否考虑增加个宽屏下自定义列数的选项，为我们这样的眼瞎患者带来福音～～

**Comment by magicdawn** [comment]
YouTube 首页体验确实不错~

**Comment by magicdawn** [comment]
现在是和 B站 其他卡片一致
- 新版首页, 屏幕最宽的时候可以到 7 列
- 内测首页, 最宽的时候 5 列

---

> 不知道作者能否考虑增加个宽屏下自定义列数的选项，为我们这样的眼瞎患者带来福音～～

它这个是 responsive 的, 加选项不太实际

**Comment by magicdawn** [comment]
1.从 YouTube 抄了点样式, 加了个设置, 可以设置成大卡片, 大间距. 可以试试

2.我把 grid 类名固定了一下, `.bilibili-app-recommend-video-grid` 用这个类名可以方便的编写样式.
