### ISSUE TITLE
[Bug]稍后观看点击后无限循环

### ISSUE THREAD

**Issue by Seraphli** [magicdawn/bilibili-app-recommend#44]
一直提示页面找不到, 然后跳转到登录, 然后页面找不到, 一直重复循环. 关掉插件就好了. 版本是0.15.0

**Comment by magicdawn** [comment]
无法复现, 请提供更多信息

**Comment by Seraphli** [comment]
如何提供?如何输出调试信息?

**Comment by Seraphli** [comment]
https://github.com/magicdawn/bilibili-app-recommend/assets/1586755/c10cd678-a164-48c0-bceb-bd26eff2627c

**Comment by Seraphli** [comment]
代码是我点击脚本主页重新安装的, 油猴上关闭脚本之后就不会出现, 隐身模式也不会出现

**Comment by magicdawn** [comment]
其他 Tab 有问题么? 

> 你可以在脚本管理器重置成默认设置, 返回默认 Tab

**Comment by Seraphli** [comment]
推荐tab没问题呀

**Comment by magicdawn** [comment]
这样操作一下,

1.切到稍后再看
2.打开 devtools, 切到 Network (网络), 勾上 perserve log (保留日志), 
3.刷新一下

然后
- 在 devtools 里搜索一下 `x/v2/history/toview/web`, 看一下响应是啥

**Comment by magicdawn** [comment]
看一下页面找不到的 url 是啥, 然后切到 "Doc" (中文 "文档"), 搜索一下, 悬浮在 initiator (中文 "初始化器" 之内的) 上看一下是谁导致这次跳转的

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/ab9e8b61-5de4-442f-ae31-b1c2d37d2382)

**Comment by Seraphli** [comment]
<img width="698" alt="image" src="https://github.com/magicdawn/bilibili-app-recommend/assets/1586755/bb0af037-08e1-4f92-a0fb-b25d84645be3">
有两个链接, 你应该用的是uri, 但是uri在插件开的时候打开是有问题的.
short那个我测试过没问题.
另外我开隐身模式, 看到的uri是同一个. 看上去并不是链接的问题, 就好像是cookie导致的?

**Comment by Seraphli** [comment]
确实, 清除cookie之后就好了, 问题解决

**Comment by magicdawn** [comment]
??? 你高兴就好

**Comment by Seraphli** [comment]
我不知道插件关闭之后cookie为什么会变化, 但是之前确实是关闭插件就好了, 并不是隐身模式, 所以才认为是插件的问题.
