### ISSUE TITLE
关于本项目获取accessToken的方式探讨

### ISSUE THREAD

**Issue by cctyl** [magicdawn/bilibili-app-recommend#45]
查看代码发现，本项目使用的是第三方登陆 https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png  来获得，这种方式相比官方的登陆，是否是可以越过人机验证

**Comment by cctyl** [comment]
其中，我看获得回调时，采用了创建一个新窗口的方式，这里有个 [issue ]( https://github.com/SocialSisterYi/bilibili-API-collect/issues/393)   ，可以直接发head请求，拿到 location。我刚刚按照本项目的方式，尝试了可行

**Comment by magicdawn** [comment]
1.本项目初版代码来自 https://github.com/indefined/UserScripts/tree/master/bilibiliHome
2.获取 access_key 这个过程没动, 是 indefined 实现的
3.我看了你提到的 issue, 是一样的, 模拟第三方登录. 
4.脚本管理器没法 发 head 请求, 然后不 follow redirect. (TamperMonkey 新版支持). 如果你的环境没有限制, 可以用 head 请求取出 access_key
