### ISSUE TITLE
一些更新建议&请求 b0.16.5

### ISSUE THREAD

**Issue by MRCUOGUO** [magicdawn/bilibili-app-recommend#46]
1.电脑端推荐Tab也添加"我不想看"选项，
- 在“我不想看”选项卡内列出视频所有标签(Tag)
选项包括：UP、所有标签(包括分区、频道)、内容过多、推荐过、不感兴趣
支持多选

- 过滤推荐算法如下：
- 对 UP 不想看，则在加载推荐列表的时候过滤掉 UP ：黑名单；
- 对 标签 不想看，根据"我不想看"某标签的次数，进行概率屏蔽
比如 "不想看"1次：10%概率对此标签进行过滤
2次：20%
以此类推，10次彻底屏蔽；

- 对 内容过多 不想看，综合视频 "频道" 进行概率屏蔽(或者更好的算法)
此过滤权重较低于"标签"
比如1次 5%或者2%，以此类推；

- 对 推荐过 不想看，过滤此视频；

- 对 不感兴趣 不想看，综合视频 "分区" 进行概率屏蔽，同“内容过多”。

2.添加屏蔽App端推荐"图文"功能(非常需要!!!);
3.添加"我想看"功能(可有可无)：
- 3.1：添加历史记录Tab，
- 3.2：在历史记录Tab中像"我不想看"选项一样添加"我想看"，
- 3.3：在"我想看"选项卡中列出视频全部Tag(包括分区、频道)，
- 3.4：选择(可多选)喜欢的Tag，
- 3.5：在下次获取推荐视频的时候，将带有"我想看"选择的Tag的视频置前。

-respect.

**Comment by MRCUOGUO** [comment]
补充：除"UP、所有标签(包括分区、频道)、内容过多、推荐过、不感兴趣"外，还有标题关键词

**Comment by magicdawn** [comment]
建议通过 B 站反馈给官方, B站应该有专门的推荐算法团队.

我这只是个第三方脚本, 啥也干不了哈!

**Comment by MRCUOGUO** [comment]
> 建议通过 B 站反馈给官方, B站应该有专门的推荐算法团队.
> 
> 我这只是个第三方脚本, 啥也干不了哈!

这些都以本地配置文件保存，算法只是随机过滤和完全过滤，应该是可以的吧，然后有个思路，就是获取视频的时候对获取到的视频链接执行一个带cookie的get，这样获取视频的接口应该就不会获取到重复的视频了，目前最需要的还是屏蔽图文的选项

**Comment by magicdawn** [comment]
- 看过的视频-不会再推荐, 这个也不一定吧~
- 而且标识看过, 肯定不是页面请求, 应该哪个接口吧!

**Comment by magicdawn** [comment]
这个想法不错: 
对 UP 不想看，则在加载推荐列表的时候过滤掉 UP ：黑名单；

我自己经常点了我不想看一个 UP, 还反复给我推荐

**Comment by magicdawn** [comment]
v0.16.6 已支持过滤图片推荐
