### ISSUE TITLE
Can the plugin be compatible with ScriptCat?

### ISSUE THREAD

**Issue by jacksen168** [magicdawn/bilibili-app-recommend#51]
# Can the plugin be compatible with ScriptCat?
能使该插件可以和脚本猫兼容吗？

**Comment by jacksen168** [comment]
## I don't usually like to use the oil monkey plugin, because I have some needs, I want the browser to run some scripts in the background. That's why I chose to use ScriptCat. ScriptCat is compatible with oil monkey scripts, but cannot save access_key and other content settings at runtime.
我平时不太喜欢用油猴插件，由于我有一些需求，要浏览器在后台运行一些脚本。因此我选择使用ScriptCat。ScriptCat是具备兼容油猴脚本的，但运行时无法保存access_key及其他内容设置。

**Comment by magicdawn** [comment]
ScriptCat `GM.setValue` 不能持久化, 不知道为什么

**Comment by magicdawn** [comment]
你可以使用支持的脚本管理器(Tampermonkey or ViolentMonkey)安装这个脚本, 与 scriptcat 并行使用. 
应该也不会冲突

**Comment by magicdawn** [comment]
dev 环境无法复现, build 版的脚本稳定复现. scriptcat 实现机制问题. 无法在这里解决

**Comment by jacksen168** [comment]
好的我已了解，谢谢你帮助

**Comment by k99k5** [comment]
> dev 环境无法复现, build 版的脚本稳定复现. scriptcat 实现机制问题. 无法在这里解决


大概试了一下，额外加了
@grant GM_setValue就可以了

**Comment by k99k5** [comment]
> 但是我只用了, `GM.xxx` API, 唯一一个 `GM_addStyle` 是 vite-plugin-monkey 生成的.
> 
> 只使用 GM.xxx API 原因是当时兼容 macOS safari Userscripts 管理器时, 那边只支持 GM.xxx API 想着兼容性更好, 就都切到 GM. API 了

貌似可以两个都加
