### ISSUE TITLE
[BUG]: 你必须登录B站之后才能使用授权

### ISSUE THREAD

**Issue by magicdawn** [magicdawn/bilibili-app-recommend#53]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)

### 问题详细描述

https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/208813

### 预期结果

https://github.com/SocialSisterYi/bilibili-API-collect/issues/393#issuecomment-1782971405

因B站接口变动, 原方法已失效.

**Comment by imtipi** [comment]
那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐

**Comment by Horrah123456** [comment]
> 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐

解决了嘛

**Comment by Horrah123456** [comment]
> ### 环境
> 浏览器: (如 Chrome) 浏览器版本: (如 113.0.5672.126) 脚本管理器: (如 暴力猴 / TamperMonkey)
> 
> ### 问题详细描述
> https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/208813
> 
> ### 预期结果
> [SocialSisterYi/bilibili-API-collect#393 (comment)](https://github.com/SocialSisterYi/bilibili-API-collect/issues/393#issuecomment-1782971405)
> 
> 因B站接口变动, 原方法已失效.

现在改如何解决？

**Comment by jerry460** [comment]
> 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐

油猴的管理面板里打开脚本-点击储存-第一行把你获取的key填入-刷新

**Comment by jerry460** [comment]
> 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐

https://github.com/XiaoMiku01/fansMedalHelper 这个项目可以获取access_key

**Comment by jerry460** [comment]
> ### 环境
> 
> 浏览器: (如 Chrome) 浏览器版本: (如 113.0.5672.126) 脚本管理器: (如 暴力猴 / TamperMonkey)
> ### 问题详细描述
> 
> https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/208813
> ### 预期结果
> 
> [SocialSisterYi/bilibili-API-collect#393 (comment)](https://github.com/SocialSisterYi/bilibili-API-collect/issues/393#issuecomment-1782971405)
> 
> 因B站接口变动, 原方法已失效.

不知道您是否有空参考一下[这个项目](https://github.com/XiaoMiku01/fansMedalHelper)进行代码的改动，我成功获取了一个access_key(不知道是不是自己的/doge)

**Comment by adeNpe** [comment]
> > 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐
> 
> 油猴的管理面板里打开脚本-点击储存-第一行把你获取的key填入-刷新
请问能否进一步明说怎么填入key，不是很懂「第一行填入key」到底填哪
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/96941933/e064d42f-1bb8-43f0-bf33-e7a4a2024ab7)

**Comment by jerry460** [comment]
> > > 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐
> > 
> > 
> > 油猴的管理面板里打开脚本-点击储存-第一行把你获取的key填入-刷新
> 
> 请问能否进一步明说怎么填入key，不是很懂「第一行填入key」到底填哪 ![image](https://user-images.githubusercontent.com/96941933/280450606-e064d42f-1bb8-43f0-bf33-e7a4a2024ab7.png)

![Screenshot 2023-11-04 at 16-50-17 Bilibili Evolved](https://github.com/magicdawn/bilibili-app-recommend/assets/61368929/fd8bace9-e803-4cdc-ac79-c9e2ba1768a4)
我跟你的第一行不一样，你先点击一次获取acesskey试试

**Comment by imtipi** [comment]
> > > 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐
> > 
> > 
> > 油猴的管理面板里打开脚本-点击储存-第一行把你获取的key填入-刷新
> 
> 请问能否进一步明说怎么填入key，不是很懂「第一行填入key」到底填哪 ![image](https://user-images.githubusercontent.com/96941933/280450606-e064d42f-1bb8-43f0-bf33-e7a4a2024ab7.png)

油猴设置将 配置模式 改成高级

**Comment by dontd1eplz** [comment]
> > > > 那我应该如何手动填写accesskey到脚本内，以及手动抓包移动端accesskey是否可以继续使用脚本的手机端推荐
> > > 
> > > 
> > > 油猴的管理面板里打开脚本-点击储存-第一行把你获取的key填入-刷新
> > 
> > 
> > 请问能否进一步明说怎么填入key，不是很懂「第一行填入key」到底填哪 ![image](https://user-images.githubusercontent.com/96941933/280450606-e064d42f-1bb8-43f0-bf33-e7a4a2024ab7.png)
> 
> ![Screenshot 2023-11-04 at 16-50-17 Bilibili Evolved](https://user-images.githubusercontent.com/61368929/280455938-fd8bace9-e803-4cdc-ac79-c9e2ba1768a4.png) 我跟你的第一行不一样，你先点击一次获取acesskey试试 我说的第一行是我图里那个存储的第一行 存储的第一行是这样的 ![Screenshot 2023-11-04 at 16-52-50 bilibili-app-recommend](https://user-images.githubusercontent.com/61368929/280456063-4caca289-14a5-46c3-b2af-087e249e31cd.png)

"Storage"tab only appears if the script hassomething saved via GM_setValue.

**Comment by SakuraSakiXD** [comment]
> 

按照这个方法把key贴进去之后刷新，首页提示的accesskey提示框是没了，但还是没法显示手机推荐内容，或许真得等作者修或者看看别的办法了吧

**Comment by imtipi** [comment]
> > 
> 
> 按照这个方法把key贴进去之后刷新，首页提示的accesskey提示框是没了，但还是没法显示手机推荐内容，或许真得等作者修或者看看别的办法了吧

如何定义无法显示，我在填入之后可以刷新，也能显示已关注的tag的视频

**Comment by magicdawn** [comment]
v0.18.0 

由于之前使用模拟第三方登录获取 access_key 方式失效, 新版支持使用手机 App 扫码, 模拟登录 TV 获取 access_key.

参考 https://socialsisteryi.github.io/bilibili-API-collect/docs/login/login_action/QR.html#tv%E7%AB%AF%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95
