### ISSUE TITLE
能不能添加钉住搜索记录的功能

### ISSUE THREAD

**Issue by PumpkinSin** [magicdawn/bilibili-app-recommend#54]
### 环境

chrome

### 问题详细描述

或者在tab右边加自定义常用搜索词乃至任何超链接，现在一些常用搜索词会被顶掉。

**Comment by magicdawn** [comment]
> 现在一些常用搜索词会被顶掉

什么意思, 这个脚本不管搜索功能啊

**Comment by PumpkinSin** [comment]
> > 现在一些常用搜索词会被顶掉
> 
> 什么意思, 这个脚本不管搜索功能啊

我意思是增加钉住功能，或者自定义超链接按钮的功能

**Comment by magicdawn** [comment]
超出范围.
