### ISSUE TITLE
视频下方没有视频发布时间的信息

### ISSUE THREAD

**Issue by wdwddog** [magicdawn/bilibili-app-recommend#55]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)

### 问题详细描述

界面看不到多久前发布的,或者可以增加按照更新时间的内容过滤,,有时候刷到太久之前的视频感觉有点扫兴,.

**Comment by magicdawn** [comment]
手机端 Api 现在是没有发布日期的, README 上有写.
