### ISSUE TITLE
[BUG]: Google Play Bilibili app 无法扫描获取access_key

### ISSUE THREAD

**Issue by wk4work** [magicdawn/bilibili-app-recommend#59]
### 环境

浏览器: Chrome
浏览器版本: 119.0.6045.200（正式版本） （64 位）
脚本管理器: TamperMonkey 4.19.0

### 问题详细描述

Google Play Bilibili app 无法扫描获取access_key

**Comment by magicdawn** [comment]
亲测, 未复现.
