### ISSUE TITLE
[BUG]:后台打开 会进入奇怪页面

### ISSUE THREAD

**Issue by juzizhen** [magicdawn/bilibili-app-recommend#63]
### 环境

浏览器: Chrome
浏览器版本: 121.0.6156.3 (正式版本) dev （64 位） (cohort: Dev)
脚本管理器: TamperMonkey

### 问题详细描述

右键的后台打开按钮打开的页面异常
预计是地址转向有误
-
**我将源码第418行的所有 /video/ 更改成了 https://www.bilibili.com/video/ 就修复了**

**Comment by magicdawn** [comment]
violentmonkey 上用没问题, tampermonkey 上确认有问题. 下个版本修复.
