### ISSUE TITLE
[BUG]:插件无法正常生效，且导致布局异常

### ISSUE THREAD

**Issue by Kal-tsit63** [magicdawn/bilibili-app-recommend#64]
### 环境

浏览器:Microsoft Edge
浏览器版本: 120.0.2210.61/120.0.2210.77      (正式版本) (64 位)
脚本管理器:Tampermonkey v5.0.6190
插件版本: github版 0.19.5

### 问题详细描述

![PixPin_2023-12-15_15-44-20](https://github.com/magicdawn/bilibili-app-recommend/assets/85188780/42187854-64e5-486f-acca-e117f5fb863b)
![PixPin_2023-12-15_16-29-44](https://github.com/magicdawn/bilibili-app-recommend/assets/85188780/46211c97-f1ae-4d5d-bac9-4dbf1b15b327)

刷新时有概率不出现，且导致主页视频卡片大小异常

另：
网页端首页已经强制改为“内测”样式，现在首页仅限当初的“内测”样式，由于内测样式置顶不太习惯，希望可以添加一个开关可选项,放到推荐下边, 作为第一个「分区」

**Comment by magicdawn** [comment]
> 希望可以添加一个开关可选项,放到推荐下边, 作为第一个「分区」
自带推荐是无限滚动的,怎么放到下边

**Comment by magicdawn** [comment]
> 刷新时有概率不出现，且导致主页视频卡片大小异常

可以找找规律, 之前没有过这样的反馈

**Comment by Kal-tsit63** [comment]
> > 希望可以添加一个开关可选项,放到推荐下边, 作为第一个「分区」
> 
> 自带推荐是无限滚动的,怎么放到下边

才发现，内测首页没有分区了，是吧？

**Comment by Kal-tsit63** [comment]
> > 刷新时有概率不出现，且导致主页视频卡片大小异常
> 
> 可以找找规律, 之前没有过这样的反馈

好，我再看看有没有规律，刚才关闭浏览器重新进入刷新，好像又不会出现了，在这之前一直都是稳定复现

**Comment by Kal-tsit63** [comment]
> > 刷新时有概率不出现，且导致主页视频卡片大小异常
> 
> 可以找找规律, 之前没有过这样的反馈

![PixPin_2023-12-15_17-15-53](https://github.com/magicdawn/bilibili-app-recommend/assets/85188780/a5feca2a-a310-490e-acb0-78d902bd7987)
控制台里好像有报错，我不知道这有没有用，抱歉，我对代码没有基础知识
另外这个bug是出现在没有使用Bilibili Evolved出现的，当时特意关掉测试，还是存在

**Comment by magicdawn** [comment]
那个警告是移除 adblock tips 的, 无关紧要.

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/d1bf4927-b020-4e3c-be87-952b131aaa56)

---

其他的 chrome插件 / 脚本 可以切换看看是不是他们导致的

**Comment by magicdawn** [comment]
should fixed in v0.19.9, if not, feel free to re-open this.
