### ISSUE TITLE
[BUG]: 鼠标悬浮视频高度异常

### ISSUE THREAD

**Issue by Infinity233** [magicdawn/bilibili-app-recommend#67]
### 环境

浏览器: Edge
浏览器版本: 120.0.2210.77 (正式版本) (64 位)
脚本管理器: Tampermonkey

### 问题详细描述

问题12.21晚突然出现，稳定复现
![Uploading 微信截图_20231221204946.png…]()

**Comment by Infinity233** [comment]
![微信截图_20231221204946](https://github.com/magicdawn/bilibili-app-recommend/assets/28898740/c85a8c35-d68b-443e-b6eb-13ff5956a7ef)

**Comment by EssentialCuber** [comment]
更新版本，已经解决了。

**Comment by EssentialCuber** [comment]
> 更新版本，已经解决了。

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/111330534/a7328345-6df4-4f07-ba73-e726cf05ff44)

**Comment by magicdawn** [comment]
用最新的...
这三个版本都能解决这个
