### ISSUE TITLE
[BUG]:鼠标悬停时预览忽大忽小，页面跳动

### ISSUE THREAD

**Issue by autumngeek** [magicdawn/bilibili-app-recommend#69]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

鼠标悬停时预览忽大忽小，页面跳动

**Comment by Dengwen-Fu** [comment]
同样问题：
环境：
@version      0.19.5
TamperMonkey
Microsoft Edge 版本 120.0.2210.77

问题详细描述
鼠标悬停时预览忽大忽小，页面跳动

**Comment by QingRex** [comment]
希望作者可以选择允许用户停用预览功能，这对我非常重要

**Comment by magicdawn** [comment]
close for duplicate of resolved issue #66 

---

可以使用暴力猴, 更新比较简单

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/e101dd2b-65f3-4bac-9bc5-3a41c0a4aa05)
