### ISSUE TITLE
[BUG]:启用BewlyBewly拓展后，在首页脚本不会自动退出

### ISSUE THREAD

**Issue by MengNianxiaoyao** [magicdawn/bilibili-app-recommend#73]
### 环境

浏览器: Chrome
浏览器版本: 120.0.6099.200
脚本管理器: TamperMonkey
脚本版本: 0.19.9

### 问题详细描述

如题，无论哪个先启用，在首页脚本都不会自动退出

**Comment by magicdawn** [comment]
会啊

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/7ce04023-57ca-45c2-9a93-dea3571ad4e2)

检测的是 `<html class='bewly-design'>` 这个 className

**Comment by MengNianxiaoyao** [comment]
> 会啊
> 
> ![image](https://private-user-images.githubusercontent.com/4067115/294884091-7ce04023-57ca-45c2-9a93-dea3571ad4e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTcxMTIsIm5iZiI6MTcwNDcxNjgxMiwicGF0aCI6Ii80MDY3MTE1LzI5NDg4NDA5MS03Y2UwNDAyMy01N2NhLTQ1YzItOWE5My1kZWEzNTcxYWQ0ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTIyNjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkxYTk1ZTRhNzg3ZDdkYjkzMmMzYjQ3ZGYwZGU3YzcxYmFkMTZlMTE5OTBmYTI4ZjM0MTEwNDczODFjNzJmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JBQ_MI2v3hjb5WdtezlWlvEx1ZseDTHLR82Egn5FE2s)
> 
> 检测的是 `<html class='bewly-design'>` 这个 className

开启纯推荐模式就会这样

**Comment by magicdawn** [comment]
quit 就是退出. 意思是检测到 BewlyBewly 之后, 这个脚本的逻辑就提前退出了, as expected.

**Comment by MengNianxiaoyao** [comment]
> quit 就是退出. 意思是检测到 BewlyBewly 之后, 这个脚本的逻辑就提前退出了, as expected.

我开启纯推荐模式就是不会退出啊，直接tryAction timeout了
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/103258286/086d79b0-115e-421d-aa8a-11efdc803449)
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/103258286/7fd0b1f4-2fe8-4f9a-87d6-9d9d7bee6018)

**Comment by magicdawn** [comment]
```
```

**Comment by magicdawn** [comment]
有时候能复现...

**Comment by magicdawn** [comment]
不知如何检测, 手动禁用其一吧.

**Comment by magicdawn** [comment]
之前只是入口检测了, 有的时候本脚本跑的比扩展快, 脚本检测不到这个 classname, 就是这种情况.
现在加了个持续检测 5s, 检测到了脚本自身就 unmount.


```js
// quit 消息
console.warn('bilibili-app-recommend: quit for using bewly-design') 

// unmount 消息
console.warn('bilibili-app-recommend: unmount for using bewly-design')
```
