### ISSUE TITLE
[BUG]：使用android端APP推荐，主页会出现一些BV号错误的视频

### ISSUE THREAD

**Issue by jipa233** [magicdawn/bilibili-app-recommend#75]
### 环境

浏览器: Edge
浏览器版本: 121.0.2277.83
脚本管理器: TamperMonkeyBeta
脚本版本: 0.20.3

### 问题详细描述

使用android端APP推荐，主页会出现一些BV号错误的视频，点进去会提示视频不见了，但是进入该UP主空间会发现该视频是存在的，但是BV号和首页推荐点进去的不一样。
例如：闲鱼上那些自带爱思助手的苹果产品是如何卖出的（20240130第29期）
首页推荐给的BV号是：BV1g34C1i7Bv
正确的BV号是：BV1vt421H7kC

**Comment by magicdawn** [comment]
v0.20.4 已发布
