### ISSUE TITLE
视频连接可以换成bvid吗

### ISSUE THREAD

**Issue by itKelis** [magicdawn/bilibili-app-recommend#8]
现在b站的视频都是以bivd为主，我另外的脚本也是判断bvid来决定接下来的操作，可以将网页连接更换为bvid吗

**Comment by magicdawn** [comment]
这个推荐数据里没有 BVID...

你可以从网页上获取
```js
document.getElementById('share_copy').value.match(/BV([\w]+)\?/)
```

![image](https://user-images.githubusercontent.com/4067115/186840751-6a768058-8931-4382-a861-5454a59b290c.png)

**Comment by magicdawn** [comment]
https://socialsisteryi.github.io/bilibili-API-collect/docs/other/bvid_desc.html#typescript

可以自己处理, 这个脚本下一版转向 BV id
