### ISSUE TITLE
[BUG]:希望可以屏蔽"关注自己的人"的视频推送

### ISSUE THREAD

**Issue by DiritoTech** [magicdawn/bilibili-app-recommend#87]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/96611541/86ca69d7-9d98-4824-a0b5-83224799dccf)
如图, app模式经常会推送自己粉丝的投稿视频

### 预期结果

不推送自己粉丝的投稿视频

**Comment by magicdawn** [comment]
反向推送, 蜜汁操作.
