### ISSUE TITLE
[BUG]:希望可以兼容“B站用户屏蔽”脚本

### ISSUE THREAD

**Issue by kukukumiko-git** [magicdawn/bilibili-app-recommend#88]
### 环境

浏览器:  Chrome
浏览器版本: 123.0.6312.107（正式版本） （64 位）
脚本管理器:TamperMonkey
脚本版本: 0.21.2

### 问题详细描述

https://greasyfork.org/zh-CN/scripts/465675-b%E7%AB%99%E7%94%A8%E6%88%B7%E5%B1%8F%E8%94%BD
https://github.com/NateScarlet/user-scripts
这是一个可以屏蔽指定用户和关键词视频的脚本
其实一开始[bilibili-app-recommend]和“B站用户屏蔽”是兼容的，额外增加的推荐视频也可以屏蔽，但近日发现屏蔽无法作用于脚本额外添加的推荐，只用于原有的推荐视频
查看油猴控制面板发现[bilibili-app-recommend]更新了一次，不知是否是这种原因

**Comment by magicdawn** [comment]
1.不保证与其他第三方脚本的兼容性. 除 readme 中列出的.

2.你可以尝试 **取消勾选** 设置中的两项自定义以获得最大的兼容性.

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/6597d11f-39e0-489e-9fac-07f9898c18ca)

3.more
- https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend/discussions/238384

**Comment by kukukumiko-git** [comment]
谢谢

**Comment by magicdawn** [comment]
https://github.com/magicdawn/bilibili-app-recommend/releases/tag/v0.24.0 设置中的"新卡片样式" 移除了
