### ISSUE TITLE
全屏模式建议

### ISSUE THREAD

**Issue by windy1021** [magicdawn/bilibili-app-recommend#89]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

大佬，能不能把推荐页的全屏模式改成只有3行，或者自定义/自适应行数？只按换一换去刷新视频，不然还要滚轮，万一滑了很久没有想看的还得回滚上去换一换 ，或者可不可以考虑把换一换按钮变成竖向排版，跟随页面滚动一直悬浮在固定位置
再申请加一个返回上一次换一换推荐内容的功能，类似于撤销按钮，防止换一换点的太快错过想看的视频
感谢大佬

**Comment by magicdawn** [comment]
1.现在是会多加载半屏. 你可以一直点换一换, 不用看多加载的部分.

2. "考虑把换一换按钮变成竖向排版，跟随页面滚动一直悬浮在固定位置", 现在是已经是固定在右上角, 也可以按 `r` 刷新. 换一换现在已经够够方便了吧...

3. "再申请加一个返回上一次换一换推荐内容的功能，类似于撤销按钮，防止换一换点的太快错过想看的视频"
这个需求太小众了...这边建议你手慢一点.

**Comment by windy1021** [comment]
好的谢谢耐心解答
