### ISSUE TITLE
能否优化一下性能？

### ISSUE THREAD

**Issue by dd178** [magicdawn/bilibili-app-recommend#9]
我是刚从旧版主页换过来的，我发现使用这个仓库的脚本换一换刷新非常慢，之前使用另一个作者的旧版主页是正常速度
![20220915195526](https://user-images.githubusercontent.com/66549247/190399026-fd367647-ad0c-4d79-9558-32895de07cc3.png)

上图可以看到从点击换一换开始到渲染花费了0.8秒！
![20220915200120](https://user-images.githubusercontent.com/66549247/190402153-f9848887-033f-4d68-b7e9-055f5133a759.png)

看了下网络请求是没问题的，我点击其他分区的换一换也是只有0.2秒不到，不知道是不是只有我是这种问题，0.8秒的刷新时间确实太长了

**Comment by magicdawn** [comment]
刷新请求在 monkey 插件的背景页 devtool 里.
![image](https://user-images.githubusercontent.com/4067115/191310018-6f0578a8-6dea-4aed-8934-9c7d5838f446.png)


已修复一处请求排队的情况, 已删除非必要的 delay, try v0.4.4
![image](https://user-images.githubusercontent.com/4067115/191312288-3ef6402d-370f-4baa-bd94-7a01acba9286.png)
