### ISSUE TITLE
[FEATURE]: 能否添加标题关键词的过滤的功能。

### ISSUE THREAD

**Issue by cyd1st** [magicdawn/bilibili-app-recommend#90]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

经常遇到带`#tag#`，这种其他平台引流过来的低劣短视频。
使用其他脚本一是可能存在兼容问题，二是功能太杂，而我只需要这么一个功能。

**Comment by magicdawn** [comment]
v0.21.6
