### ISSUE TITLE
[BUG]:视频卡片右键菜单 会被系统自带的覆盖住 无法正常使用 

### ISSUE THREAD

**Issue by hug1013** [magicdawn/bilibili-app-recommend#92]
### 环境

浏览器: (Chrome)
浏览器版本: (124.0.6367.156)
脚本管理器: (tampermonkey)
脚本版本: (0.21.8)

### 问题详细描述

脚本的视频卡片右键菜单功能 会被浏览器的鼠标右键功能覆盖住 无法正常使用 
偶尔还无法触发 视频卡片右键菜单功能
在之前的版本是正常可以使用视频卡片右键菜单功能的
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/86723248/f7163618-21a6-4ff4-9a05-c7a4e083dd7f)

**Comment by magicdawn** [comment]
1. 我是 macOS, 无法重现
2. 这里很久没动了, 不知道跟 antd 升级有没有关系; 
3. 我修改了一个版本 b9e56f5, 你可以测试看看, 安装 [最新开发版](https://github.com/magicdawn/bilibili-app-recommend/raw/release-nightly/bilibili-app-recommend.mini.user.js)

**Comment by magicdawn** [comment]
closing for no feedback & patch released in v0.21.9 (several days ago)
