### ISSUE TITLE
请求添加竖屏ui[BUG]:

### ISSUE THREAD

**Issue by dragonaptx4869** [magicdawn/bilibili-app-recommend#96]
### 环境

浏览器: edge
浏览器版本: (如 113.0.5672.126)
脚本管理器: (如 暴力猴 / TamperMonkey)
脚本版本: (如 0.14.0, 请先更新到最新版本!!!)

### 问题详细描述

![屏幕截图(24)](https://github.com/magicdawn/bilibili-app-recommend/assets/45513790/57a2319c-c95f-4bc8-8c33-14d319500013)
如图，竖屏情况下标签太小了，每行两个大小应该合适

**Comment by magicdawn** [comment]
`shift + C`

**Comment by magicdawn** [comment]
居中模式: 一个我觉得没多大用的功能, 可能可以用于你这个场景.
如果还有问题. 可以再打开 issue.
