### ISSUE TITLE
[BUG]: 视频宽高比大于1预览图会变形

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#97]
### 环境

浏览器: Edge
浏览器版本: 125.0.2535.51
脚本管理器: TamperMonkey
脚本版本: 0.21.8

### 问题详细描述

鼠标悬浮在宽高比大于1的视频上，如4:3或21:9，预览图被拉伸填满卡片
![屏幕截图 2024-05-22 185730](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/9df7047c-4b09-49a6-8787-342b0cb4088c)

### 预期结果

希望能像宽高比小于或等于1的视频，如竖屏或正方形的视频，保持原始比例
![屏幕截图 2024-05-22 191445](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/e5b222b1-4529-40db-ba39-03528efdc53e)

**Comment by magicdawn** [comment]
bvid

**Comment by magicdawn** [comment]
BV1qm421W7Sb, 确实有这个情况.

不过缩略图是B站自己生成的, https://bimp.hdslb.com/videoshotpvhdboss/1531960369_ij5m5b-0001.jpg
虽然视频不是 16/9 的, 但是缩略图生成的是 480 / 270, 也就是 16 / 9.

这里我这边控制不了. 要解决只能换真的视频预览, 但我觉得缩略图用于预览还挺方便的. 所以暂只能这样.

-----

介意的话, 看推荐还有很多其他的方案:

- 自带首页 + 一系列屏蔽插件(比如 bilibili-cleaner)
- BewlyBewly

**Comment by magicdawn** [comment]
有 API 可以, 但不值得为了极少数的视频去做这件事.
