### ISSUE TITLE
[BUG]:动态中看不到更新的番剧

### ISSUE THREAD

**Issue by Rocstellar** [magicdawn/bilibili-app-recommend#99]
### 环境

浏览器: Edge
浏览器版本: 124.0.2478.80 (正式版本) (64 位)
脚本管理器: TamperMonkey
脚本版本: 0.22.2

### 问题详细描述

番剧更新后，官方的动态页面中有红点显示，而脚本中没有
![PixPin_2024-05-25_11-22-39](https://github.com/magicdawn/bilibili-app-recommend/assets/65894668/f58bc296-1595-40af-9e81-30cd5122c6f8)

![PixPin_2024-05-25_11-23-05](https://github.com/magicdawn/bilibili-app-recommend/assets/65894668/f7f78c0a-7155-4b0d-ab3a-ff729ebd3441)

**Comment by magicdawn** [comment]
是不支持, 现在只支持 "视频投稿"

![image](https://github.com/magicdawn/bilibili-app-recommend/assets/4067115/c2dfa9b5-6f24-44e1-bb20-096ca6ac0e3a)

需要看其他, 如 "追番追剧", "专栏", 去动态页看吧

追番追剧 https://t.bilibili.com/?tab=pgc
专栏 https://t.bilibili.com/?tab=article
